#ansible playbook that prints the hostname of the server

- hosts: all
  become: yes
  tasks:
    - name: print hostname
      shell: hostname
      register: hostname
    - name: print hostname
      debug:
        msg: "{{hostname.stdout}}"
    - name: apt update
      apt:
        update_cache: yes
    - name: install docker
      apt:
        name: docker.io
        state: present
    #start dockerd
    - name: start docker
      service:
        name: docker
        state: started

    - name: delete containers
      docker_container:
        name: discbot
        state: absent
    - name: delete image
      docker_image:
        name: ghcr.io/antjpcdrogas/discbot:latest
        state: absent

    - name: pull image
      docker_image:
        name: ghcr.io/antjpcdrogas/discbot:latest
        source: pull
    #run image
    - name: run image
      docker_container:
        name: discbot
        image: ghcr.io/antjpcdrogas/discbot:latest
        restart_policy: always
        state: started
        env:
          BOT_TOKEN: "{{ BOT_TOKEN }}"
          OPENAI_API_KEY: "{{ OPENAI_API_KEY }}"
          botDiscId: "{{ botDiscId }}"
          channelId: "{{ channelId }}"
          guildId: "{{ guildId }}"
          SPEECH_KEY: "{{ SPEECH_KEY }}"
