name: Docker Image CI

on:
  ##commit message contains image

  push:
    branches: ["docker-image"]
    # paths:
    #   - "infra/**"
jobs: # must run on ubuntu and use Container registry to push image
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository_owner }}/chatgptvoicediscbot/discbot:latest
