name: Docker Image CI

on:
  ##commit message contains image

  push:
    branches: ["docker-image"]
    # paths:
    #   - "infra/**"
jobs: # must run on ubuntu
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: docker.pkg.github.com/${{ github.repository }}/my-image:latest
