name: Docker Image CI

on:
  ##commit message contains image

  push:
    branches: ["main"]
    # any path change expect infra
    paths-ignore:
      - "infra/**"
jobs: # must run on ubuntu and use Container registry to push image
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/discbot:latest
        env:
          BOT_TOKEN: ${{secrets.NODE_DISC_API_KEY}}
