name: Docker Image CI

on:
  push:
    branches: ["main"]
    # paths:
    #   - "infra/**"
jobs: # must run on ubuntu
  build:
    runs-on: ubuntu-latest
    #must have terraform installed. After installing, init the "infra" folder using -chdir flag, and run terraform plan

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform -chdir=infra init
      - name: Terraform Plan ## save play.out as artifact
        run: terraform -chdir=infra plan -out=plan.out
      - name: Terraform Apply
        run: terraform -chdir=infra apply -auto-approve plan.out
      - name: Terraform Destroy
        run: terraform -chdir=infra destroy -auto-approve
      - name: Terraform Destroy
        run: terraform -chdir=infra destroy -auto-approve

  #    - uses: actions/checkout@v3
  #    - name: Build the Docker image
  #      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
